### ISSUE TITLE
Glitches

### ISSUE THREAD

**Issue by NoSie** [OpenMacroBoard/StreamDeckSharp#16]
Hi,

not sure if this is still relevant and probably you did this already. But have you tried updating the firmware on your StreamDeck via the original elgato software? This seemed to have solved all glitching problems for me...

Hope this helps and thanks for your cool API!

**Comment by wischi-chr** [comment]
Hi, Thanks for your comment.

I took a quick look and it seems like the glitches were fixed. 🎉 

The solution I wrote (`CachedHidClient`) is still relevant because it also deals with the fact that writing images to the stream deck takes time and if it's done synchrounously it halts the current thread and may block your UI thread if you are not careful.

It's the default mode but can be disabled (can help during debugging), because if you hit a beakpoint after SetKeyBitmap you can be sure that the image was already sent to the device, in cached mode that's not the case but it's "faster" because it doesn't block.
