### ISSUE TITLE
Streamdeck Rev.2 and XL some times have Displayissues 

### ISSUE THREAD

**Issue by patrick-dmxc** [OpenMacroBoard/StreamDeckSharp#23]
When you send many Frames in a short time. the Images are disturted/corrupted.

There is a Video in our Bugtracker:
https://bugs.dmxcontrol-projects.org/index.php?do=details&task_id=3957

And a conversation in our Forum:
https://forum.dmxcontrol-projects.org/index.php?thread/14869-stream-deck-setting-up-and-using-with-input-assignment/&postID=126789#post126789

**Comment by wischi-chr** [comment]
Can you provide a simple repo link to reproduce this issue. I have a streamdeck xl and don't see any issues.

**Comment by wischi-chr** [comment]
Could you try to run the image glitch example code:
https://github.com/OpenMacroBoard/OpenMacroBoard.ExampleCollection/tree/master/src/OpenMacroBoard.Examples.ImageGlitchTest

Both settings (synchronous and fast) don't produce any artifacts for me on my StreamDeck XL
![Anmerkung 2020-03-11 224249](https://user-images.githubusercontent.com/2495113/76467330-ada4a600-63e9-11ea-9a7b-055e6998e307.png)

If you want to try synchronous mode in your application (disables fast asynchronous writes to the device) you can set `IStreamDeckRefHandle.UseWriteCache` before calling `.Open()`

**Comment by wischi-chr** [comment]
Ok found it. 🎉 

I downloaded DMXControl3 and could reproduce the glitches immediately.

After a few hours of puzzle solving _(which I really enjoyed)_ I found out that it only happens when `AbstractMacroBoardManager.StartAnimation` is finished, but StreamDeckSharp is still writing the bitmap and `inputManager.RegisterSource()` is already registering all `KeyButtonInputSources`

**The glitch happens because the serial number is read while the bitmap is still being written.**

You can try it for yourself by replacing the `GetSerialNumber()` call inside `IMacroBoardExtentions.GetSerialNumber` with a hard coded string return.

It's definitely a bug in StreamDeckSharp and I will fix that in the next few days and keep you updated.

**Comment by wischi-chr** [comment]
@patrick-dmxc I released a new version on nuget. Could you try it and let me know if it works for you. Thanks

**Comment by patrick-dmxc** [comment]
oh sorry for not answering.
I was busy

but that was very quick now.
I will now update and add our beta testers to it. I still have Rev. 1, I can't test it.

**Comment by patrick-dmxc** [comment]
It works with the new Version
Thanks
