### ISSUE TITLE
not working with .netcore3.1

### ISSUE THREAD

**Issue by det-peralta** [OpenMacroBoard/StreamDeckSharp#29]
I cannot use the dependency OpenMacroBoard.SDK on my .netcore, any plans to support this?

<TargetFramework>netcoreapp3.1</TargetFramework>

![image](https://user-images.githubusercontent.com/35231379/98418596-26442b00-207b-11eb-8973-84aeaf24929f.png)

**Comment by det-peralta** [comment]
I find the problem when im installing StreamDeckSharp 2.2.0 nuget, it installs OpenMacroBoard.SDK 2.0.0 version.

**SOLVED**: i installed first OpenMacroBoard.SDK 2.1.0 and then StreamDeckSharp 2.2.0  

:shipit:

**Comment by wischi-chr** [comment]
Sorry took a while. The dependency on OpenMacroBoard was "theoretically" valid, that's why I did't catch it during development, but .NET has pretty strict rules what versions can be referenced. If the assembly is not strong-named only the exact version it was built against is allowed.

So the most recent update now uses strong-named assemblies.

Let me know if it works for you.
