### ISSUE TITLE
Streamdeck shows button for split second, then returns to show the Elgato logo

### ISSUE THREAD

**Issue by Coow** [OpenMacroBoard/StreamDeckSharp#41]
Hi!

Started playing around with this library, and I tried to get a simple button working. 
I already have the Counter Example plugin as an example on my Streamdeck on button 0, and then I try to add a White Button on button1.

When the app starts, it displays the White Button for a split second, then clears ALL the buttons to display the Elgato Logo. After that if I click on the buttons it returns to the Streamdeck config, so if I clickthe Counter it will return to normal. Any idea?

**Comment by wischi-chr** [comment]
I guess there are a few things going on. This library os a low level library that directly communicates with the StreamDeck (without Elgatos StreamDeck Software) make sure that this is what you want. If you want to write a plugin for the official software pls use Elgatos SDK.

If you want direct stream deck communication for example to roll you own software (without the need of the elgato software) or do stuff like playing fullscreen videos on the stream deck this library is probably a good fit.

First make sure you only have one program running that communicates with the stream deck (this means you have to close the official software). If you don't do that the programs might overwrite each others actions.

Now back to this library. You have to make sure your software (that uses this library) keeps running while you do stuff. All the examples are console applications that do this by blocking the main console thread until you press Ctrl+C - alternatively you could create a WinForms or WPF application because they already come with a message loop and will only close when you press the close button.

**Comment by wischi-chr** [comment]
Closed because of inactivity. Let me know if you need more help.
