### ISSUE TITLE
System.MissingMethodException: Method not found: 'Void SixLabors.ImageSharp.Formats.Jpeg.JpegEncoder.set_Quality(System.Nullable`1<Int32>)'

### ISSUE THREAD

**Issue by temppase** [OpenMacroBoard/StreamDeckSharp#57]
I got this kind a error  message when trying to initialize stream deck.

**Comment by temppase** [comment]
It was pointing on this line: streamDeck = StreamDeck.OpenDevice();

**Comment by wischi-chr** [comment]
Hi @temppase 

It looks like you updated `SixLabors.ImageSharp` to version 3 but this major version step is not supported by `StreamDeckSharp` you should switch to `v2.1.8`

The reason is that `StreamDeckSharp` also supports the .NET Framework and the new v3 version for `SixLabors.ImageSharp` does not, so I still target the v2 variant of `ImageSharp`.

Maybe in the future I might drop the .net framework support, or only use image sharp v2 for .net framework and v3 for .net core which should simplify things, but for now the only option is ImageSharp v2

**Comment by temppase** [comment]
Ok thanks

to 25. huhtik. 2024 klo 14.24 Christian Franzl ***@***.***>
kirjoitti:
