### ISSUE TITLE
Support for StreamDeck + via Nuget

### ISSUE THREAD

**Issue by PhillyNJ** [OpenMacroBoard/StreamDeckSharp#60]
Hi,

Any plans to update the Nuget package to support Stream Deck +? I am currently using version 6.0 from Nuget and its not recognized. 

Thanks in advance.

**Comment by wischi-chr** [comment]
Hi @PhillyNJ 

Sadly I'm not sure when I'll find the time to implement it, because it requires a rewrite of the entire interface (`IMacroBoard` & Co).
There is also already a tracking issue for the Stream Deck + support here #50, so I'm closing this issue, but feel free to comment on the other issue.
